apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    #   image: some-image
    # This is the ambassador container
    - name: basic
      image: nginx
      volumeMounts:
      - name: basic-config
        mountPath: /etc/nginx/conf.d
  volumes:
    - name: basic-config
      configMap:
        name: basic-config