apiVersion: v1
kind: Pod
metadata:
  name: splitter-pod
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    #   image: some-image
    # This is the ambassador container
    - name: splitter
      image: nginx
      volumeMounts:
      - name: splitter-config
        mountPath: /etc/nginx/conf.d
  volumes:
    - name: splitter-config
      configMap:
        name: splitter-config